services:
    admin.post:
        class: %dipsycat_post.admin_class%
        arguments: [~, %dipsycat_post.entity_class%, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Post }
        public: true